import { Geist, Geist_Mono } from "next/font/google";
import { Playfair_Display } from 'next/font/google';
import "./globals.css";
import Navbar from "../components/navbar/Navbar";

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair.className} ${playfair.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
